### PR TITLE
Add slack to readme

### PR DESCRIPTION
**Pull request by xmclark**
Now we have a slack channel!

okcupidjs.slack.com

### CODE REVIEW

**Comment by xmclark** [comment]
I think we need to setup slackin for automating invites

**Comment by tranhungt** [comment]
Here's the link for auto invites. https://publicslack.com/slacks/okcupidjs/invites/new
I'll merge and add it. I'll also add this to the top of readme so everybody sees it.

**Comment by xmclark** [comment]
@tranhungt this is great! Thanks! I am going to repopen this PR and add that link too.

**Comment by xmclark** [comment]
@tranhungt scratch that, you beat me to it :)

**Pull request merged**
