### PR TITLE
Add methods to send and receive messages 

### PR DESCRIPTION
**Pull request by xmclark**

### CODE REVIEW

**Comment by xmclark** [comment]
Fixes issue #4

**Comment by tranhungt** [comment]
Looks perfect. Could you add to the readme as well?

**Comment by xmclark** [comment]
Oh good idea. On it...

**Comment by xmclark** [comment]
I've added some documentation, as well as explanation of the structures returned. No need to make the app dev look around for what he needs in the response.

**Comment by tranhungt** [comment]
Very nice! Thanks for the detailed documentation. That looks awesome! :)

**Pull request merged**
