### PR TITLE
Add editProfile method

### PR DESCRIPTION
**Pull request by PierrickGT**

### CODE REVIEW

**Comment by tranhungt** [comment]
@PierrickGT Thanks for the PR! Could you please add documentation on how to use this endpoint? And what are all the {editCategory} available to use?

@xmclark Was this similar to something you wanted to implement to edit profile?

**Comment by xmclark** [comment]
Yes. Somebody had made a comment on #13 suggesting they had a PR but looks like that was ages ago.

**Comment by PierrickGT** [comment]
I've added a description and a small query sample.
For now, I just know about the essay category endpoint but I guess there are other endpoints that you can edit.

For example, you can edit your profile by making a `PUT` request to the following endpoint `https://www.okcupid.com/1/apitun/profile/me`

**Comment by tranhungt** [comment]
Thanks @PierrickGT, Thanks @xmclark.

**Pull request merged**
